/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author sergio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItemDeptos = new javax.swing.JMenuItem();
        jMenuItemTourist = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mnuDeptos = new javax.swing.JMenuItem();
        mnuActivity = new javax.swing.JMenuItem();
        mnuTown = new javax.swing.JMenuItem();
        mnuPlace = new javax.swing.JMenuItem();
        mnuTouristPlace = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Reportes");

        jMenuItemDeptos.setText("Deptos");
        jMenuItemDeptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeptosActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItemDeptos);

        jMenuItemTourist.setText("Tourist");
        fileMenu.add(jMenuItemTourist);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Formularios");

        mnuDeptos.setMnemonic('t');
        mnuDeptos.setText("Departamentos");
        mnuDeptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeptosActionPerformed(evt);
            }
        });
        editMenu.add(mnuDeptos);

        mnuActivity.setText("Actividades");
        editMenu.add(mnuActivity);

        mnuTown.setText("Ciudades");
        mnuTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTownActionPerformed(evt);
            }
        });
        editMenu.add(mnuTown);

        mnuPlace.setText("Tipo de lugar");
        editMenu.add(mnuPlace);

        mnuTouristPlace.setText("Sitio Turistico");
        editMenu.add(mnuTouristPlace);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItemDeptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeptosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeptosActionPerformed

    private void mnuDeptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeptosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuDeptosActionPerformed

    private void mnuTownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuTownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    public javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    public javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    public javax.swing.JMenuItem jMenuItemDeptos;
    public javax.swing.JMenuItem jMenuItemTourist;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem mnuActivity;
    public javax.swing.JMenuItem mnuDeptos;
    public javax.swing.JMenuItem mnuPlace;
    public javax.swing.JMenuItem mnuTouristPlace;
    public javax.swing.JMenuItem mnuTown;
    // End of variables declaration//GEN-END:variables

}
